"""sales foundation

Revision ID: 0003_sales_foundation
Revises: 0002_crm_foundation
Create Date: 2026-10-02
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0003_sales_foundation"

down_revision: Union[str, Sequence[str], None] = (
    "0002_crm_foundation"
)

branch_labels: Union[str, Sequence[str], None] = None

depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "pipelines",
        sa.Column(
            "name",
            sa.String(length=150),
            nullable=False,
        ),
        sa.Column(
            "is_default",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "organization_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "name",
            name="uq_pipeline_org_name",
        ),
    )

    op.create_index(
        op.f("ix_pipelines_organization_id"),
        "pipelines",
        ["organization_id"],
    )

    op.create_table(
        "pipeline_stages",
        sa.Column(
            "pipeline_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "probability",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.String(length=30),
            server_default="open",
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "organization_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "probability >= 0 AND probability <= 100",
            name="ck_pipeline_stages_probability_range",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "pipeline_id",
            "name",
            name="uq_pipeline_stage_name",
        ),
        sa.UniqueConstraint(
            "pipeline_id",
            "position",
            name="uq_pipeline_stage_position",
        ),
    )

    op.create_index(
        op.f("ix_pipeline_stages_pipeline_id"),
        "pipeline_stages",
        ["pipeline_id"],
    )

    op.create_index(
        op.f("ix_pipeline_stages_organization_id"),
        "pipeline_stages",
        ["organization_id"],
    )

    op.create_index(
        op.f("ix_pipeline_stages_category"),
        "pipeline_stages",
        ["category"],
    )

    op.create_table(
        "opportunities",
        sa.Column(
            "name",
            sa.String(length=250),
            nullable=False,
        ),
        sa.Column(
            "account_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "primary_contact_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "pipeline_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "stage_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "owner_user_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "amount",
            sa.Numeric(18, 2),
            nullable=True,
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            server_default="USD",
            nullable=False,
        ),
        sa.Column(
            "probability",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "expected_close_date",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "closed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "organization_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "probability >= 0 AND probability <= 100",
            name="ck_opportunities_probability_range",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["primary_contact_id"],
            ["contacts.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["pipeline_stages.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    for column in [
        "name",
        "account_id",
        "primary_contact_id",
        "pipeline_id",
        "stage_id",
        "owner_user_id",
        "expected_close_date",
        "organization_id",
    ]:
        op.create_index(
            op.f(
                f"ix_opportunities_{column}"
            ),
            "opportunities",
            [column],
        )

    op.create_table(
        "leads",
        sa.Column(
            "first_name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "last_name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "email",
            sa.String(length=320),
            nullable=True,
        ),
        sa.Column(
            "phone",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "company_name",
            sa.String(length=250),
            nullable=True,
        ),
        sa.Column(
            "job_title",
            sa.String(length=150),
            nullable=True,
        ),
        sa.Column(
            "source",
            sa.String(length=80),
            server_default="manual",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            server_default="new",
            nullable=False,
        ),
        sa.Column(
            "score",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "owner_user_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "converted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "converted_account_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "converted_contact_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "converted_opportunity_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "organization_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "score >= 0 AND score <= 100",
            name="ck_leads_score_range",
        ),
        sa.ForeignKeyConstraint(
            ["converted_account_id"],
            ["accounts.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["converted_contact_id"],
            ["contacts.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["converted_opportunity_id"],
            ["opportunities.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    for column in [
        "email",
        "company_name",
        "source",
        "status",
        "owner_user_id",
        "organization_id",
    ]:
        op.create_index(
            op.f(
                f"ix_leads_{column}"
            ),
            "leads",
            [column],
        )


def downgrade() -> None:
    op.drop_table("leads")
    op.drop_table("opportunities")
    op.drop_table("pipeline_stages")
    op.drop_table("pipelines")
