"""engagement foundation

Revision ID: 0004_engagement_foundation
Revises: 0003_sales_foundation
Create Date: 2026-10-02
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = (
    "0004_engagement_foundation"
)

down_revision: Union[
    str,
    Sequence[str],
    None,
] = "0003_sales_foundation"

branch_labels: Union[
    str,
    Sequence[str],
    None,
] = None

depends_on: Union[
    str,
    Sequence[str],
    None,
] = None


def upgrade() -> None:
    op.add_column(
        "activities",
        sa.Column(
            "lead_id",
            sa.Uuid(),
            nullable=True,
        ),
    )

    op.add_column(
        "activities",
        sa.Column(
            "opportunity_id",
            sa.Uuid(),
            nullable=True,
        ),
    )

    op.create_foreign_key(
        "fk_activities_lead_id_leads",
        "activities",
        "leads",
        ["lead_id"],
        ["id"],
        ondelete="SET NULL",
    )

    op.create_foreign_key(
        (
            "fk_activities_"
            "opportunity_id_opportunities"
        ),
        "activities",
        "opportunities",
        ["opportunity_id"],
        ["id"],
        ondelete="SET NULL",
    )

    op.create_index(
        op.f(
            "ix_activities_lead_id"
        ),
        "activities",
        ["lead_id"],
    )

    op.create_index(
        op.f(
            "ix_activities_opportunity_id"
        ),
        "activities",
        ["opportunity_id"],
    )

    op.create_table(
        "email_threads",
        sa.Column(
            "provider",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "external_thread_id",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "subject",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "snippet",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "account_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "contact_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "opportunity_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "participants",
            postgresql.JSONB(),
            server_default=sa.text(
                "'[]'::jsonb"
            ),
            nullable=False,
        ),
        sa.Column(
            "last_message_at",
            sa.DateTime(
                timezone=True
            ),
            nullable=True,
        ),
        sa.Column(
            "organization_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(
                timezone=True
            ),
            server_default=sa.text(
                "now()"
            ),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(
                timezone=True
            ),
            server_default=sa.text(
                "now()"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "provider",
            "external_thread_id",
            name=(
                "uq_email_threads_"
                "org_provider_external"
            ),
        ),
    )

    op.create_index(
        op.f(
            "ix_email_threads_provider"
        ),
        "email_threads",
        ["provider"],
    )

    op.create_index(
        op.f(
            "ix_email_threads_external_thread_id"
        ),
        "email_threads",
        ["external_thread_id"],
    )

    op.create_index(
        op.f(
            "ix_email_threads_account_id"
        ),
        "email_threads",
        ["account_id"],
    )

    op.create_index(
        op.f(
            "ix_email_threads_contact_id"
        ),
        "email_threads",
        ["contact_id"],
    )

    op.create_index(
        op.f(
            "ix_email_threads_opportunity_id"
        ),
        "email_threads",
        ["opportunity_id"],
    )

    op.create_index(
        op.f(
            "ix_email_threads_last_message_at"
        ),
        "email_threads",
        ["last_message_at"],
    )

    op.create_index(
        op.f(
            "ix_email_threads_organization_id"
        ),
        "email_threads",
        ["organization_id"],
    )

    op.create_index(
        "ix_email_threads_org_last_message_at",
        "email_threads",
        [
            "organization_id",
            "last_message_at",
        ],
    )

    op.create_table(
        "email_messages",
        sa.Column(
            "thread_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "provider",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "external_message_id",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "account_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "contact_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "opportunity_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "direction",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "subject",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "from_address",
            sa.String(length=320),
            nullable=False,
        ),
        sa.Column(
            "from_name",
            sa.String(length=250),
            nullable=True,
        ),
        sa.Column(
            "to_recipients",
            postgresql.JSONB(),
            server_default=sa.text(
                "'[]'::jsonb"
            ),
            nullable=False,
        ),
        sa.Column(
            "cc_recipients",
            postgresql.JSONB(),
            server_default=sa.text(
                "'[]'::jsonb"
            ),
            nullable=False,
        ),
        sa.Column(
            "bcc_recipients",
            postgresql.JSONB(),
            server_default=sa.text(
                "'[]'::jsonb"
            ),
            nullable=False,
        ),
        sa.Column(
            "reply_to",
            sa.String(length=320),
            nullable=True,
        ),
        sa.Column(
            "body_text",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "body_html",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "snippet",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(
                timezone=True
            ),
            nullable=False,
        ),
        sa.Column(
            "is_read",
            sa.Boolean(),
            server_default=sa.text(
                "false"
            ),
            nullable=False,
        ),
        sa.Column(
            "is_draft",
            sa.Boolean(),
            server_default=sa.text(
                "false"
            ),
            nullable=False,
        ),
        sa.Column(
            "has_attachments",
            sa.Boolean(),
            server_default=sa.text(
                "false"
            ),
            nullable=False,
        ),
        sa.Column(
            "attachments",
            postgresql.JSONB(),
            server_default=sa.text(
                "'[]'::jsonb"
            ),
            nullable=False,
        ),
        sa.Column(
            "internet_message_id",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "in_reply_to",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "references",
            postgresql.JSONB(),
            server_default=sa.text(
                "'[]'::jsonb"
            ),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(),
            server_default=sa.text(
                "'{}'::jsonb"
            ),
            nullable=False,
        ),
        sa.Column(
            "organization_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(
                timezone=True
            ),
            server_default=sa.text(
                "now()"
            ),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(
                timezone=True
            ),
            server_default=sa.text(
                "now()"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["email_threads.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "provider",
            "external_message_id",
            name=(
                "uq_email_messages_"
                "org_provider_external"
            ),
        ),
    )

    for column in [
        "thread_id",
        "provider",
        "external_message_id",
        "account_id",
        "contact_id",
        "opportunity_id",
        "direction",
        "occurred_at",
        "internet_message_id",
        "organization_id",
    ]:
        op.create_index(
            op.f(
                f"ix_email_messages_{column}"
            ),
            "email_messages",
            [column],
        )

    op.create_index(
        "ix_email_messages_org_occurred_at",
        "email_messages",
        [
            "organization_id",
            "occurred_at",
        ],
    )

    op.create_index(
        "ix_email_messages_thread_occurred_at",
        "email_messages",
        [
            "thread_id",
            "occurred_at",
        ],
    )

    op.create_table(
        "meetings",
        sa.Column(
            "provider",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "external_event_id",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "account_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "contact_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "opportunity_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "organizer_user_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "title",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "location",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "meeting_url",
            sa.String(length=1000),
            nullable=True,
        ),
        sa.Column(
            "start_at",
            sa.DateTime(
                timezone=True
            ),
            nullable=False,
        ),
        sa.Column(
            "end_at",
            sa.DateTime(
                timezone=True
            ),
            nullable=False,
        ),
        sa.Column(
            "timezone",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            server_default="scheduled",
            nullable=False,
        ),
        sa.Column(
            "attendees",
            postgresql.JSONB(),
            server_default=sa.text(
                "'[]'::jsonb"
            ),
            nullable=False,
        ),
        sa.Column(
            "is_all_day",
            sa.Boolean(),
            server_default=sa.text(
                "false"
            ),
            nullable=False,
        ),
        sa.Column(
            "is_online",
            sa.Boolean(),
            server_default=sa.text(
                "false"
            ),
            nullable=False,
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "summary",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "action_items",
            postgresql.JSONB(),
            server_default=sa.text(
                "'[]'::jsonb"
            ),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(),
            server_default=sa.text(
                "'{}'::jsonb"
            ),
            nullable=False,
        ),
        sa.Column(
            "organization_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(
                timezone=True
            ),
            server_default=sa.text(
                "now()"
            ),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(
                timezone=True
            ),
            server_default=sa.text(
                "now()"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organizer_user_id"],
            ["users.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "provider",
            "external_event_id",
            name=(
                "uq_meetings_"
                "org_provider_external"
            ),
        ),
    )

    for column in [
        "provider",
        "external_event_id",
        "account_id",
        "contact_id",
        "opportunity_id",
        "organizer_user_id",
        "start_at",
        "status",
        "organization_id",
    ]:
        op.create_index(
            op.f(
                f"ix_meetings_{column}"
            ),
            "meetings",
            [column],
        )

    op.create_index(
        "ix_meetings_org_start_at",
        "meetings",
        [
            "organization_id",
            "start_at",
        ],
    )


def downgrade() -> None:
    op.drop_table(
        "meetings"
    )

    op.drop_table(
        "email_messages"
    )

    op.drop_table(
        "email_threads"
    )

    op.drop_index(
        op.f(
            "ix_activities_opportunity_id"
        ),
        table_name="activities",
    )

    op.drop_index(
        op.f(
            "ix_activities_lead_id"
        ),
        table_name="activities",
    )

    op.drop_constraint(
        (
            "fk_activities_"
            "opportunity_id_opportunities"
        ),
        "activities",
        type_="foreignkey",
    )

    op.drop_constraint(
        "fk_activities_lead_id_leads",
        "activities",
        type_="foreignkey",
    )

    op.drop_column(
        "activities",
        "opportunity_id",
    )

    op.drop_column(
        "activities",
        "lead_id",
    )
